# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 16:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=4)),
                ('gênero', models.CharField(max_length=9)),
                ('deh_nascimento', models.CharField(max_length=9)),
                ('deh_cadastro', models.DateField(verbose_name=datetime.datetime(2017, 2, 20, 13, 37, 51, 324442))),
            ],
        ),
    ]
