# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 17:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReACT_API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atleta',
            name='deh_cadastro',
        ),
        migrations.AlterField(
            model_name='atleta',
            name='deh_nascimento',
            field=models.DateField(verbose_name=datetime.datetime(2017, 2, 20, 14, 4, 2, 307524)),
        ),
    ]
