# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 17:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReACT_API', '0002_auto_20170220_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='deh_cadastro',
            field=models.DateField(default=datetime.datetime(2017, 2, 20, 14, 5, 10, 890382)),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='deh_nascimento',
            field=models.CharField(max_length=9),
        ),
    ]
