# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReACT_API', '0003_auto_20170220_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='deh_cadastro',
            field=models.DateField(default=datetime.datetime(2017, 2, 23, 15, 17, 17, 565958)),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='deh_nascimento',
            field=models.DateField(),
        ),
    ]
